version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: saludplus_postgres
    restart: always
    environment:
      POSTGRES_USER: user_salud
      POSTGRES_PASSWORD: password_salud
      POSTGRES_DB: saludplus_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo-db:
    image: mongo:6
    container_name: saludplus_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: